### ISSUE TITLE
All channels are down...

### ISSUE THREAD

**Issue by mrrneo** [kungpfui/plugin.video.swisscom_tv_unofficial#1]
Hi,
I tried to access the TV channels in Kodi and none of them work.

**Comment by kungpfui** [comment]
Well, maybe they are all down because you are not a Swisscom TV customer or/and you are not connected to their network. Swisscom TV is not for free.
My plugin just allows to use Kodi to watch some of their TV channels as long you are a Swisscom customer. Nothing more and nothing less.
